require("dotenv").config();
require("./db");
const express = require("express");
const app = express();
const cors = require("cors");
const http = require("http");
const corsList = process.env.urlList || [];
//const server = http.createServer(server);
const cookieParser = require("cookie-parser");
const { auth } = require("./libs/auth");
const port = process.env.PORT;
// console.log(corsList.split(","));
app.use(express.json());
app.use(cookieParser());
app.use(express.static("public"));
app.use(cors({ origin: corsList.split(","), credentials: true }));
app.use(auth);
app.use(require("./router"));

app.listen(port, () => console.log(`Server Start at ${port}`));
