module.exports = {
  PORT: process.env.PORT || 4001,
  DB_URL: process.env.DB_URL,
  SECRETKEY: process.env.SECRETKEY,
  ADMIN_SECRET: process.env.ADMIN_SECRET,

  MAIL_USER: process.env.MAIL_USER,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  MAIL_REDIRECT_URL: process.env.MAIL_REDIRECT_URL,
  GOOGLE_AUTH_CALLBACK: process.env.GOOGLE_AUTH_CALLBACK,
  MAIL_REFRESH_TOKEN: process.env.MAIL_REFRESH_TOKEN,

  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
  FACEBOOK_AUTH_CALLBACK: process.env.FACEBOOK_AUTH_CALLBACK,


  BASE_URL: process.env.BASE_URL,
  ADMIN_URL: process.env.ADMIN_URL,
  API_URL: process.env.API_URL,
  ESEWA_GATEWAY_URL: process.env.ESEWA_GATEWAY_URL,
  ESEWA_PRODUCT_CODE: process.env.ESEWA_PRODUCT_CODE,
  ESEWA_SECRET: process.env.ESEWA_SECRET,
  KHALTI_GATEWAY_URL: process.env.KHALTI_GATEWAY_URL,
  KHALTI_SERECT_KEY: process.env.KHALTI_SERECT_KEY

}